import { registerMathCopy } from '../src/lib/mathCopy'
import { check, equal, type RenderMath } from './math-copy.cases'

let dispose: (() => void) | undefined
let before = ''
let copyEvent: { trusted: boolean; handled: boolean; text: string; html: string } | undefined

/** The driver sends real Ctrl/Cmd-C and Ctrl/Cmd-V, not synthetic clipboard events. */
export function nativeFixture(render: RenderMath, scenario: string) {
  dispose?.()
  document.getElementById('native-fixture')?.remove()
  const host = document.createElement('div')
  host.id = 'native-fixture'
  const content = scenario === 'display'
    ? `<p>Before.</p>${render(String.raw`\begin{aligned}x&=1\\y&=2\end{aligned}`, true)}<p>After.</p>`
    : scenario === 'ordinary'
      ? `<p id="ordinary">Ordinary <strong>text</strong>.</p><p>${render('x^2')}</p>`
      : `<h2>Euler equation</h2><p>The equation is ${render("u'(c_t)=\\beta(1+r)u'(c_{t+1})")}, which describes allocation.</p><ul><li>First ${render('x^2')}</li><li>Second</li></ul>`
  host.innerHTML = `<div class="md" id="native-source">${content}</div><textarea id="native-plain"></textarea><div id="native-rich" contenteditable="true"></div>`
  document.body.append(host)
  const source = host.querySelector<HTMLElement>('#native-source')!
  const stop = registerMathCopy(source)
  const record = (e: ClipboardEvent) => {
    copyEvent = { trusted: e.isTrusted, handled: e.defaultPrevented, text: e.clipboardData?.getData('text/plain') || '', html: e.clipboardData?.getData('text/html') || '' }
  }
  document.addEventListener('copy', record)
  dispose = () => { stop(); document.removeEventListener('copy', record) }
  before = source.innerHTML
  copyEvent = undefined
  const range = document.createRange()
  range.selectNodeContents(scenario === 'ordinary' ? source.querySelector('#ordinary')! : source)
  const selection = document.getSelection()!
  selection.removeAllRanges(); selection.addRange(range)
}

export function nativeResult(scenario: string) {
  const source = document.getElementById('native-source')!
  const plain = (document.getElementById('native-plain') as HTMLTextAreaElement).value
  const rich = document.getElementById('native-rich')!
  const expected = scenario === 'ordinary' ? 'Ordinary text.' : scenario === 'display'
    ? 'Before.\n\nx = 1\ny = 2\n\nAfter.'
    : 'Euler equation\n\nThe equation is u′(cₜ) = β(1 + r)u′(cₜ₊₁), which describes allocation.\n\n• First x²\n• Second'
  try {
    check(copyEvent?.trusted, 'The driver must trigger a trusted native copy event')
    equal(copyEvent.handled, scenario !== 'ordinary')
    equal(source.innerHTML, before)
    equal(plain, expected)
    check(!rich.querySelector('math, annotation, .katex, svg'), 'Renderer content reappeared on rich-text paste')
    // List bullets are generated by the editor, not part of its textContent.
    equal(rich.innerText.replace(/\s+/g, ' ').trim(), expected.replace(/• /g, '').replace(/\s+/g, ' ').trim())
    if (scenario === 'mixed') check(rich.querySelector('h2') && rich.querySelectorAll('li').length === 2, 'Rich formatting was lost')
    return { plain, richHTML: rich.innerHTML, event: copyEvent }
  } finally { dispose?.(); dispose = undefined }
}
